### ISSUE TITLE
UI-Konzept

### ISSUE THREAD

**Issue by astrutz** [astrutz/eloglicko#1]
- Grobes Konzept, wie die einzelnen Features UI-seitig platziert werden
- ggf. Auswahl von passenden UI-Elementen aus Vuetify o.ä.
- SPA
- Library zur Darstellung von Graphen finden (d.3)

**Comment by Snapstromegon** [comment]
![Whiteboard 1 -01](https://user-images.githubusercontent.com/18480654/139873047-99f106ff-f2e2-4431-a5a7-ecb24a3ce174.png)
