### ISSUE TITLE
Create common base types for all rating systems

### ISSUE THREAD

**Issue by Snapstromegon** [astrutz/eloglicko#8]
There are some base types to be created which are common among all rating systems and which are used to interface with the UI.

These types are:

- [x] Player
  - [x] name
  - [x] color
  - [x] strength
  - [x] test to win against other player
- [x] PlayerRating
  - [x] Manage the current rating
  - [x] keep a history of ratings
- [x] Ranking
  - [x] keep a list of players
  - [x] keep a list of player rankings
  - [x] get deviations from current ranking to expected
  - [x] calculate player positions
  - [x] allow to sort player rankings
  - [x] create some simple match creation methods
- [ ] ...

**Comment by astrutz** [comment]
- [ ] Tournament
  - [ ] keep a list of all tournaments (played and to be played)
  - [ ] keep a list of all games (played and to be played) 
  - [ ] keep a list of all ranking changes within a tournament (not sure if really needed)
